---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhenfeng.xzf.
--- DateTime: 2019/6/2 上午10:36
---


if (not ngx.var.arg_time) then
    ngx.exit(400)
else
    ngx.say("pass param check")
end