---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhenfeng.xzf.
--- DateTime: 2019/6/2 下午1:29
---

local function check_white_ip(ip, ip_list)
    for k, v in ipairs(ip_list) do
        if v == ip then
            return true
        end
    end
    return false
end


local white_list = {'127.0.0.1'}

local ip = ngx.var.remote_addr

ip_check = check_white_ip(ip, white_list)

if not ip_check then
    ngx.log(ngx.ERR, ip, " is blocked")
    ngx.exit(403)
end